config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :notes
  root 'home#index'
  get 'home/about'
  get 'home/contact'
  get 'home/faq'
  get 'home/profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable

  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def faq
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!#, except: [:index, :show] #wyjątek w uwierzytelnianiu dla stron index i show
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Notatka została utworzona' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Notatka została zaktualizowana' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Notatka została usunięta' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :content)
    end
  def correct_user
    @note = current_user.notes.find_by(id: params[:id])
    redirect_to notes_path, notice: "Nie posiadasz odpowiednich uprawnień" if @note.nil?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/faq.html.erb
<div class="containerr">
	<div class="box">
		<h1>Catch me</h1></br>
		<p>if you can</p>
	</div>
</div>

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Edu Lab</h1>
    <p class="lead">Wkrótce więcej</p>
  </div>
</div>

app/views/home/profile.html.erb
<% if current_user.admin? %>
	<h1>Witaj nauczycielu</h1>
<% else %>
	<h1>Witaj uczniu</h1>
<% end %>

<%= link_to 'Edycja profilu', edit_user_registration_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to image_tag('logo_min.jpg', height: '32', width: '32') + ' Edu Lab', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <%= link_to 'O mnie', home_about_path, class: 'nav-item active nav-link tooltips', title: '', data: { toggle: 'tooltip', placement: 'top', original_title: 'Znajdziesz tutaj info o mnie' } %>
      <%= link_to 'FAQ', home_faq_path, class: 'nav-item nav-link' %>
      <%= link_to 'Kontakt', home_contact_path, class: 'nav-item nav-link' %>
      <% if user_signed_in? %>
        <%= link_to 'Notatki', notes_path , class: 'nav-item nav-link' %>
        <%= link_to 'Profil', home_profile_path, class: 'nav-item nav-link' %>
        <%= link_to 'Wyloguj', destroy_user_session_path, method: :delete, class: 'nav-item nav-link' %>
      <% else %>
        <%= link_to 'Rejestracja', new_user_registration_path, class: 'nav-item nav-link' %>
        <%= link_to 'Logowanie', new_user_session_path, class: 'nav-item nav-link' %>
      <% end %>
      <span class="d-inline-block" data-toggle="popover" data-content="Na razie nie klykej">
      	<li class="nav-item">
        	<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      	</li>
      </span>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Edu Lab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "styles" %>
  </head>

  <body>
    <%= render 'layouts/header' %><br />
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <% if note.user == current_user %>
        <tr>
          <td><%= note.title %></td>
          <td><%= note.content %></td>
          <td><%= link_to 'Show', note %></td>
          <td><%= link_to 'Edit', edit_note_path(note) %></td>
          <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

<% if @note.user == current_user %>
  <%= link_to 'Edit', edit_note_path(@note) %> |
<% end %>
<%= link_to 'Back', notes_path %>